#!/usr/bin/env python3
"""Generate native, grayscale-antialiased VLW fonts for M5GFX. No runtime filesystem."""
import argparse
import hashlib
from pathlib import Path
import struct

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/fonts/BarlowSemiCondensed-SemiBold.ttf"
SOURCE_SHA256 = "bd299f4bc5b44d30be8d42e9bad3a5df7d66af1cd55d0ed72a8b8916360a1424"
OUTPUT = ROOT / "firmware/eight_sleep_button/StatusFonts.h"
ASCII = "".join(chr(c) for c in range(33, 127))
SPECS = (("Title", 41, ASCII), ("Busy", 38, "Sending"), ("Detail", 21, ASCII))


def make_font(size, characters):
    font = ImageFont.truetype(str(SOURCE), size)
    glyphs = {}
    for char in sorted(set(characters)):
        left, top, right, bottom = font.getbbox(char, anchor="ls")
        width, height = right - left, bottom - top
        mask = Image.new("L", (width, height))
        ImageDraw.Draw(mask).text((-left, -top), char, font=font, anchor="ls", fill=255)
        advance = round(font.getlength(char))
        assert 0 < width < 256 and 0 < height < 256
        assert 0 < advance < 256 and -128 <= left < 128
        glyphs[char] = (height, width, advance, -top, left, mask)
    ascent = max(g[3] for g in glyphs.values())
    descent = max(g[0] - g[3] for g in glyphs.values())
    # M5GFX derives space width from these bounds and ignores the nominal size.
    result = bytearray(struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent))
    for char, (height, width, advance, dy, dx, _) in glyphs.items():
        result.extend(struct.pack(">7i", ord(char), height, width, advance, dy, dx, 0))
    for *_, mask in glyphs.values():
        result.extend(mask.tobytes())
    return bytes(result), glyphs, ascent, descent


def text_width(text, font):
    _, glyphs, ascent, descent = font
    left = right = 0
    for char in text:
        if char == " ":
            width = advance = (ascent + descent) * 2 // 7
            dx = 0
        else:
            _, width, advance, _, dx, _ = glyphs[char]
        if left == right == 0 and dx < 0:
            left = right = -dx
        right = left + max(advance, width + dx)
        left += advance
    return right


def render_line(image, text, y, font, color):
    _, glyphs, ascent, descent = font
    width = text_width(text, font)
    assert width <= 124, (text, width)
    x = (128 - width) // 2
    for char in text:
        if char == " ":
            x += (ascent + descent) * 2 // 7
            continue
        height, width, advance, dy, dx, mask = glyphs[char]
        assert y + ascent - dy >= 0 and y + ascent - dy + height <= 128
        image.paste(color, (x + dx, y + ascent - dy), mask)
        x += advance


def preview(fonts, destination):
    # Same native glyph masks, integer advances, space width, positions and colors
    # as the firmware. This is a layout preview, not a simulation of LCD brightness.
    variants = (
        ("Started", (150, 230, 185), "Rapid", "Cooling", "Started"),
        ("Active", (150, 230, 185), "Rapid", "Cooling", "Already active"),
        ("Busy", (240, 185, 85), "Sending", "", ""),
        ("Failure", (245, 130, 110), "Failed", "", "Check app"),
        ("Status", (155, 195, 240), "Status", "", "Wi-Fi OK"),
        ("Setup", (240, 185, 85), "Set up", "", "Setup needed"),
    )
    sheet = Image.new("RGB", (3 * 136 + 8, 2 * 136 + 8), (40, 40, 40))
    for index, (_, color, title, second, detail) in enumerate(variants):
        screen = Image.new("RGB", (128, 128))
        if second:
            render_line(screen, title, 5, fonts["Title"], color)
            render_line(screen, second, 48, fonts["Title"], color)
        else:
            render_line(screen, title, 44 if not detail else 25,
                        fonts["Busy"] if title == "Sending" else fonts["Title"], color)
        if detail:
            render_line(screen, detail, 101 if second else 83, fonts["Detail"], color)
        sheet.paste(screen, (8 + (index % 3) * 136, 8 + (index // 3) * 136))
    destination.parent.mkdir(parents=True, exist_ok=True)
    sheet.resize((sheet.width * 3, sheet.height * 3), Image.Resampling.NEAREST).save(destination)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the checked-in header without changing it")
    parser.add_argument("--preview", type=Path, help="Optional layout contact sheet")
    args = parser.parse_args()
    if hashlib.sha256(SOURCE.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise SystemExit("Font source checksum mismatch")
    fonts = {name: make_font(size, characters) for name, size, characters in SPECS}
    lines = ["// Generated by scripts/generate_fonts.py; do not edit.",
             "// Barlow Semi Condensed SemiBold, SIL OFL 1.1; see assets/fonts/OFL.txt.",
             "#pragma once", "#include <stdint.h>", "", "namespace status_fonts {"]
    for name, font in fonts.items():
        data = font[0]
        lines.append(f"alignas(4) static const uint8_t k{name}[] = {{")
        lines.extend("  " + ", ".join(f"0x{b:02x}" for b in data[i:i+16]) + ","
                     for i in range(0, len(data), 16))
        lines.append("};")
        print(f"{name}: {len(data)} bytes; {font[2] + font[3]}-pixel line height")
    lines.append("}  // namespace status_fonts\n")
    generated = "\n".join(lines)
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit("Generated font header differs; run scripts/generate_fonts.py")
    else:
        OUTPUT.write_text(generated)
    if args.preview:
        preview(fonts, args.preview)


if __name__ == "__main__":
    main()
